import Head from "next/head";
import { useRouter } from "next/dist/client/router";
import { useState, useEffect } from "react";
import styles from "../../styles/Home.module.css";
import ImageUrlBuilder from "@sanity/image-url";
import PostCard from "../../components/PostCard";

export default function Home({ selected }) {
  const router = useRouter();
  const post = selected;
  const [mappedPost, setmappedPost] = useState([]);
  useEffect(() => {
    if (post.length) {
      const imgBuilder = ImageUrlBuilder({
        projectId: "7gx68era",
        dataset: "production",
        apiVersion: "2021-10-21",
        useCdn: true,
      });

      setmappedPost(
        post.map((p) => {
          return {
            ...p,
            mainImage: imgBuilder.image(p.mainImage),
          };
        })
      );
    }
  }, [post]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Your web blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {mappedPost.length ? (
            mappedPost.map((item, key) => {
              return <PostCard key={key} item={item} />;
            })
          ) : (
            <p></p>
          )}
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const query = encodeURIComponent(`*[ _type == "post" ]`);
  const url = `https://7gx68era.api.sanity.io/v1/data/query/production?query=${query}`;
  const results = await fetch(url).then((res) => res.json());
  const post = results.result;
  const selected = post.filter((item) => {
    if (item.tags.includes(context.query.slug)) {
      return item;
    }
    return;
  });

  if (!selected.length) {
    return {
      notFound: true,
    };
  } else {
    return {
      props: {
        selected,
      },
    };
  }
};
