import Head from "next/head";
import { useRouter } from "next/dist/client/router";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import ImageUrlBuilder from "@sanity/image-url";

export default function Home({ post }) {
  const router = useRouter();

  const [mappedPost, setmappedPost] = useState([]);
  useEffect(() => {
    if (post.length) {
      const imgBuilder = ImageUrlBuilder({
        projectId: "7gx68era",
        dataset: "production",
        apiVersion: "2021-10-21",
        useCdn: true,
      });

      setmappedPost(
        post.map((p) => {
          return {
            ...p,
            mainImage: imgBuilder.image(p.mainImage),
          };
        })
      );
    }
  }, [post]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Your web blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {mappedPost.length ? (
            mappedPost.map((item, key) => {
              return (
                <div
                  onClick={() => router.push(`/post/${item.slug.current}`)}
                  key={key}
                  className={styles.card}
                >
                  <img src={item.mainImage} alt="article cover" />
                  <h2>{item.title}</h2>
                  <p>{item.description}</p>
                  <ul className={styles.taglist}>
                    {item.tags.map((tag, key) => {
                      return (
                        <li className={styles.tag} key={key}>
                          {tag}
                        </li>
                      );
                    })}
                  </ul>
                </div>
              );
            })
          ) : (
            <p></p>
          )}
        </div>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const query = encodeURIComponent(`*[ _type == "post" ]`);
  const url = `https://7gx68era.api.sanity.io/v1/data/query/production?query=${query}`;
  const results = await fetch(url).then((res) => res.json());
  const post = results.result;

  if (!post) {
    return {
      notFound: true,
    };
  } else {
    return {
      props: {
        post,
      },
    };
  }
};
