import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import cover from "../assets/display.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Your web blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.card}>
            <Image
              layout="responsive"
              width={400}
              height={250}
              src={cover}
              alt="article cover"
            />
            <h2>Documentation and development of react</h2>
            <p>Find in-depth information about Next.js features and API.</p>
            <ul className={styles.taglist}>
              <li className={styles.tag}>javascript</li>
            </ul>
          </div>

          <div className={styles.card}>
            <Image
              layout="responsive"
              width={400}
              height={250}
              src={cover}
              alt="article cover"
            />
            <h2>Learn React from scratch</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
            <ul className={styles.taglist}>
              <li className={styles.tag}>react js</li>
              <li className={styles.tag}>css</li>
              <li className={styles.tag}>javascript</li>
            </ul>
          </div>

          <div className={styles.card}>
            <Image
              layout="responsive"
              width={400}
              height={250}
              src={cover}
              alt="article cover"
            />
            <h2>Examples of better css code</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
            <ul className={styles.taglist}>
              <li className={styles.tag}>next js</li>
              <li className={styles.tag}>html</li>
            </ul>
          </div>

          <div className={styles.card}>
            <Image
              width={400}
              layout="responsive"
              height={250}
              src={cover}
              alt="article cover"
            />
            <h2>Deploy and manage your app in next</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
            <ul className={styles.taglist}>
              <li className={styles.tag}>next js</li>
              <li className={styles.tag}>html</li>
              <li className={styles.tag}>python</li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
}
